#K-means

##Load Data

In [ ]:
!pip install plotly --upgrade

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [ ]:
x = [20,  27,  21,  37,  46, 53, 55,  47,  52,  32,  39,  41,  39,  48,  48]  
y = [1000,1200,2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]  

In [ ]:
graph = px.scatter(x = x, y = y)
graph.show()

In [ ]:
salary_base = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],
                        [53,950],[55,2000],[47,2100],[52,3000],[32,5900],
                        [39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])

In [ ]:
scaler_salary = StandardScaler()
salary_base = scaler_salary.fit_transform(salary_base)

In [ ]:
model = KMeans(n_clusters=3)
model.fit(salary_base)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [ ]:
centers = model.cluster_centers_
centers

array([[ 0.73953003, -0.72661025],
       [ 0.07703438,  1.11413572],
       [-1.63312883, -0.77505093]])

In [ ]:
scaler_salary.inverse_transform(model.cluster_centers_)

array([[  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ],
       [  22.66666667, 1700.        ]])

In [ ]:
labels = model.labels_
labels

array([2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int32)

In [13]:
graph1 = px.scatter(x = salary_base[:,0], y = salary_base[:,1], color=labels)
graph2 = px.scatter(x = centers[:,0], y = centers[:,1], size = [12, 12, 12])
graph3 = go.Figure(data = graph1.data + graph2.data)
graph3.show()