In [2]:
import numpy as np # Math Library

a = np.array([1, 2, 3]) # All elements of the same type
print(a)

[1 2 3]


In [3]:
b = np.array([(2, 5, 7), (5, 3, 9)])
print (b)

[[2 5 7]
 [5 3 9]]


In [4]:
c = np.zeros((4, 3)) # Matrix 4 lines x 3 columns
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
c = np.eye(10) # Diagonal Square Matrix
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [6]:
print('Maximum:', b.max())
print('Minimum:', b.min())
print('Mean:', b.mean())
print('Standard Deviation:', b.std())

Maximum: 9
Minimum: 2
Mean: 5.166666666666667
Standard Deviation: 2.3392781412697
