In [1]:
import pandas as pd
data = pd.read_excel("..//Data//Teste.xlsx")

In [2]:
data.head() # First 5 lines

Números Letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e

In [3]:
data.head(6) # First 6 lines

Números Letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e
5        6      f

In [6]:
data_2 = pd.read_csv("..//Data//athlete_events.csv")

In [7]:
data_2.head(6)

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   
5   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   
5  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                                Event Medal  
0         Basketball Men's Basketball   NaN  
1        Judo Men's Extra-Lightweight   NaN  
2             Football Men's Football   NaN  
3         Tug-Of-War Men's Tug-Of-War  Gold  
4    Speed Skating Women's 500 metres   NaN  
5  Speed Skating Women's 1,000 metres   NaN

In [8]:
students = {'Nome' : ['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
        'Nota': [4, 7, 5.5, 9],
        'Aprovado': ['Não', 'Sim', 'Não', 'Sim']}

In [9]:
# A data frame is similar to an array, 
# but the columns have names and can contain data of a different type. 
# A data frame can be seen as a table in a database, 
# where each row corresponds to a record in the table.

dataframe = pd.DataFrame(students)

In [10]:
print(dataframe) # Create Indexes

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim


In [11]:
object_1 = pd.Series([2, 6, 9, 10, 5])
print(object_1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [12]:
import numpy as np
array_1 = np.array([6, 12, 2, 9, 10])
array_2 = np.array([(2, 6, 9, 10, 5), (6, 12, 2, 9, 10)])
print(array_1)
print(array_2)

[ 6 12  2  9 10]
[[ 2  6  9 10  5]
 [ 6 12  2  9 10]]


In [13]:
object_2 = pd.Series(array_1)
print(object_2)

0     6
1    12
2     2
3     9
4    10
dtype: int32
