In [29]:
import tensorflow as tf

In [30]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])
b = tf.constant([[0, 0], [1, 0], [0, 1]])

In [31]:
print(tf.Session().run(b))

[[0 0]
 [1 0]
 [0 1]]


In [32]:
result = tf.matmul(a, b) # Matrix multiplication
print(tf.Session().run(result))

[[2 3]
 [5 6]]


In [33]:
x = tf.constant([0, 1, 0])
print(tf.Session().run(x))

[0 1 0]


In [34]:
print(x.shape)

(3,)


In [35]:
x = tf.expand_dims(x, 1) # Expands the dimension on the vertical axis
print(x.shape)

(3, 1)


In [38]:
resultado_2 = tf.matmul(a, x)
print(tf.Session().run(resultado_2))

[[2]
 [5]]


In [39]:
transposed = tf.transpose(a)

In [41]:
print(tf.Session().run(a))

[[1 2 3]
 [4 5 6]]


In [42]:
print(tf.Session().run(transposed))

[[1 4]
 [2 5]
 [3 6]]
