#Linear Regresion

##Health Insurance Data Base

In [1]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("plano_saude2.csv")

In [3]:
data

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [36]:
X = data.iloc[:, 0:1].values
X

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [37]:
y = data.iloc[:, 1].values
y

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [38]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X = poly.fit_transform(X)
X.shape

(10, 3)

In [39]:
X

array([[1.000e+00, 1.800e+01, 3.240e+02],
       [1.000e+00, 2.300e+01, 5.290e+02],
       [1.000e+00, 2.800e+01, 7.840e+02],
       [1.000e+00, 3.300e+01, 1.089e+03],
       [1.000e+00, 3.800e+01, 1.444e+03],
       [1.000e+00, 4.300e+01, 1.849e+03],
       [1.000e+00, 4.800e+01, 2.304e+03],
       [1.000e+00, 5.300e+01, 2.809e+03],
       [1.000e+00, 5.800e+01, 3.364e+03],
       [1.000e+00, 6.300e+01, 3.969e+03]])

In [40]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
#b0               b1
model.intercept_, model.coef_

(-16682.17183547655,
 array([ 0.00000000e+00,  2.84707318e+03, -1.82159246e+02,  5.61261885e+00,
        -8.31207649e-02,  4.80000087e-04]))

In [32]:
new = poly.transform([[40]])
model.predict(new)

array([1316.41892541])

In [33]:
predictions = model.predict(X)
predictions

array([  459.65019917,   555.85091298,   601.53855999,   810.83919704,
        1159.06759158,  1562.72725453,  2059.51047302,  2988.29834322,
        5169.16080312, 10083.35666535])

In [41]:
graph = px.scatter(x=data.iloc[:, 0].values, y=y)
graph.add_scatter(x=data.iloc[:, 0].values, y=predictions, name="Regression")
graph.show()