#Linear Regresion

##Health Insurance Data Base

In [2]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("plano_saude2.csv")

In [4]:
data

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [5]:
X = data.iloc[:, 0:1].values
X

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [6]:
y = data.iloc[:, 1].values
y

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [7]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X = poly.fit_transform(X)
X.shape

(10, 3)

In [8]:
X

array([[1.000e+00, 1.800e+01, 3.240e+02],
       [1.000e+00, 2.300e+01, 5.290e+02],
       [1.000e+00, 2.800e+01, 7.840e+02],
       [1.000e+00, 3.300e+01, 1.089e+03],
       [1.000e+00, 3.800e+01, 1.444e+03],
       [1.000e+00, 4.300e+01, 1.849e+03],
       [1.000e+00, 4.800e+01, 2.304e+03],
       [1.000e+00, 5.300e+01, 2.809e+03],
       [1.000e+00, 5.800e+01, 3.364e+03],
       [1.000e+00, 6.300e+01, 3.969e+03]])

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
scaler = StandardScaler()
y = scaler.fit_transform(y.reshape(-1,1))

In [19]:
from sklearn.neural_network import MLPRegressor
model = MLPRegressor(max_iter=1000)
model.fit(X, y)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1342: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(100,), learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=1000,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=None, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, verbose=False,
             warm_start=False)

In [20]:
new = poly.transform([[40]])
model.predict(new)

array([2020.85072984])

In [21]:
predictions = model.predict(X)
predictions

array([-0.72082935, -0.68988063, -0.65213471, -0.61473738, -0.57911818,
       -0.47761089, -0.20824779,  0.44519624,  1.29158887,  2.20313036])

In [22]:
graph = px.scatter(x=data.iloc[:, 0].values, y=y)
graph.add_scatter(x=data.iloc[:, 0].values, y=predictions, name="Regression")
graph.show()