#Linear Regresion

##House Prices Data Base

In [14]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [15]:
data = pd.read_csv("house_prices.csv")

In [16]:
data

id             date  ...  sqft_living15  sqft_lot15
0      7129300520  20141013T000000  ...           1340        5650
1      6414100192  20141209T000000  ...           1690        7639
2      5631500400  20150225T000000  ...           2720        8062
3      2487200875  20141209T000000  ...           1360        5000
4      1954400510  20150218T000000  ...           1800        7503
...           ...              ...  ...            ...         ...
21608   263000018  20140521T000000  ...           1530        1509
21609  6600060120  20150223T000000  ...           1830        7200
21610  1523300141  20140623T000000  ...           1020        2007
21611   291310100  20150116T000000  ...           1410        1287
21612  1523300157  20141015T000000  ...           1020        1357

[21613 rows x 21 columns]

In [17]:
data.describe()

id         price  ...  sqft_living15     sqft_lot15
count  2.161300e+04  2.161300e+04  ...   21613.000000   21613.000000
mean   4.580302e+09  5.400881e+05  ...    1986.552492   12768.455652
std    2.876566e+09  3.671272e+05  ...     685.391304   27304.179631
min    1.000102e+06  7.500000e+04  ...     399.000000     651.000000
25%    2.123049e+09  3.219500e+05  ...    1490.000000    5100.000000
50%    3.904930e+09  4.500000e+05  ...    1840.000000    7620.000000
75%    7.308900e+09  6.450000e+05  ...    2360.000000   10083.000000
max    9.900000e+09  7.700000e+06  ...    6210.000000  871200.000000

[8 rows x 20 columns]

In [18]:
data.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [19]:
X = data.iloc[:, 3:19].values
X

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]])

In [20]:
y = data.iloc[:,2].values
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [22]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_tr = poly.fit_transform(X_train)
X_ts = poly.transform(X_test)

In [23]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_tr, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
model.intercept_, model.coef_

(26106520541.05523,
 array([ 3.31890997e+02,  1.23091839e+07, -1.67270451e+07, -2.15561258e+04,
        -1.20415034e+02, -4.17377142e+07,  1.25068090e+08,  3.46214981e+06,
         2.46146904e+06, -1.71286937e+07,  6.49652409e+04,  1.83333845e+03,
        -1.22329857e+05,  4.02503675e+04, -6.75883399e+05,  1.13257753e+08,
        -7.41089202e+07, -7.85547741e+02,  3.57633622e+03,  1.55598867e+02,
        -7.65644106e-03,  2.33561183e+04, -9.59359905e+03,  3.06318959e+03,
        -5.76012221e+03,  6.20227624e+03, -1.75282141e+02, -1.65087151e+02,
        -4.15581799e+02, -8.21683475e+00, -2.74694935e+01, -2.84406228e+04,
         6.11618207e+04, -1.14057569e+04,  1.83624893e+01, -2.18872210e-01,
        -3.06378747e+04, -4.66692734e+04,  1.10155399e+04, -1.07915737e+04,
         4.87534024e+03,  2.58475701e+01, -8.12897852e+00,  4.39306189e+02,
        -2.66480624e+01,  3.43146110e+01,  5.24917263e+04, -8.20214709e+04,
        -1.38798932e+02, -6.42079308e+03, -6.86005788e+00,  1.342695

In [26]:
model.score(X_ts, y_test)

0.7954385759749405

In [28]:
predictions = model.predict(X_ts)

In [29]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))
mae, mse, rmse

(102513.80529333097, 25383541044.806164, 159322.12980250473)