#Linear Regresion

##Health Insurance Data Base

In [ ]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("plano_saude2.csv")

In [ ]:
data

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [ ]:
X = data.iloc[:, 0:1].values
X

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [ ]:
y = data.iloc[:, 1].values
y

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X = poly.fit_transform(X)
X.shape

(10, 3)

In [ ]:
X

array([[1.000e+00, 1.800e+01, 3.240e+02],
       [1.000e+00, 2.300e+01, 5.290e+02],
       [1.000e+00, 2.800e+01, 7.840e+02],
       [1.000e+00, 3.300e+01, 1.089e+03],
       [1.000e+00, 3.800e+01, 1.444e+03],
       [1.000e+00, 4.300e+01, 1.849e+03],
       [1.000e+00, 4.800e+01, 2.304e+03],
       [1.000e+00, 5.300e+01, 2.809e+03],
       [1.000e+00, 5.800e+01, 3.364e+03],
       [1.000e+00, 6.300e+01, 3.969e+03]])

In [26]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=10)
model.fit(X, y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [27]:
predictions = model.predict(X)
predictions

array([ 523.,  533.,  592.,  822., 1118., 1530., 1785., 3225., 5398.,
       8398.])

In [28]:
model.score(X, y)

0.9625367231466461

In [29]:
graph = px.scatter(x=data.iloc[:, 0].values, y=y)
graph.add_scatter(x=data.iloc[:, 0].values, y=predictions, name="Regression")
graph.show()