#Linear Regresion

##Health Insurance Data Base

In [ ]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("plano_saude.csv")

In [ ]:
data

idade  custo
0     18    871
1     23   1132
2     28   1242
3     33   1356
4     38   1488
5     43   1638
6     48   2130
7     53   2454
8     58   3066
9     63   4090

In [ ]:
X = data.iloc[:, 0].values
X

array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63])

In [ ]:
y = data.iloc[:, 1].values
y

array([ 871, 1132, 1242, 1356, 1488, 1638, 2130, 2454, 3066, 4090])

In [ ]:
np.corrcoef(X, y)

array([[1.        , 0.93091958],
       [0.93091958, 1.        ]])

In [ ]:
X = X.reshape(-1,1)
X.shape

(10, 1)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
#b0               b1
model.intercept_, model.coef_

(-558.9490909090912, array([61.86787879]))

In [ ]:
predictions = model.predict(X)
predictions

array([ 554.67272727,  864.01212121, 1173.35151515, 1482.69090909,
       1792.03030303, 2101.36969697, 2410.70909091, 2720.04848485,
       3029.38787879, 3338.72727273])

In [ ]:
X.ravel() # Matrix to vector

array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63])

In [ ]:
graph = px.scatter(x=X.ravel(), y=y)
graph.add_scatter(x=X.ravel(), y=predictions)
graph.show()